# Generated by Django 4.1 on 2022-11-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='confirm_password',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='uploaded_files',
            name='book_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='uploaded_files',
            name='published_year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
